# Copyright (c) 2026 Rajeh Taher
#
# Licensed under the MIT License. See LICENSE-MIT for details.

services:
  barback:
    image: hypermeow-benchmark-barback:latest
    build: !reset null
    pull_policy: never
